CUDNN:
  BENCHMARK: true
  DETERMINISTIC: false
  ENABLED: true
GPUS: (0,1,2)
OUTPUT_DIR: 'output'
LOG_DIR: 'log'
WORKERS: 8
PRINT_FREQ: 10

CACHE_DIR: 'cached_samples/cocostuff'

DATASET:
  DATASET: cocostuff
  ROOT: 'HRNet-Semantic-Segmentation/data/'
  TEST_SET: 'list/cocostuff/testval.lst'
  TRAIN_SET: 'list/cocostuff/train.lst'
  NUM_CLASSES: 171
  ABSTAIN_LABEL: 254
  HIERARCHY: 'cocostuff/cocostuff_hierarchy.json'
  THRESHOLD_FUNCTION: [0, 0.3, 0.7]

MODEL:
  NAME: seg_hrnet_ocr
  NUM_OUTPUTS: 2
  PRETRAINED: 'pretrained_models/HRNet_W48_C_ssld_pretrained.pth'
  EXTRA:
    FINAL_CONV_KERNEL: 1
    STAGE1:
      NUM_MODULES: 1
      NUM_RANCHES: 1
      BLOCK: BOTTLENECK
      NUM_BLOCKS:
      - 4
      NUM_CHANNELS:
      - 64
      FUSE_METHOD: SUM
    STAGE2:
      NUM_MODULES: 1
      NUM_BRANCHES: 2
      BLOCK: BASIC
      NUM_BLOCKS:
      - 4
      - 4
      NUM_CHANNELS:
      - 48
      - 96
      FUSE_METHOD: SUM
    STAGE3:
      NUM_MODULES: 4
      NUM_BRANCHES: 3
      BLOCK: BASIC
      NUM_BLOCKS:
      - 4
      - 4
      - 4
      NUM_CHANNELS:
      - 48
      - 96
      - 192
      FUSE_METHOD: SUM
    STAGE4:
      NUM_MODULES: 3
      NUM_BRANCHES: 4
      BLOCK: BASIC
      NUM_BLOCKS:
      - 4
      - 4
      - 4
      - 4
      NUM_CHANNELS:
      - 48
      - 96
      - 192
      - 384
      FUSE_METHOD: SUM
LOSS:
  USE_OHEM: true
  OHEMTHRES: 0.9
  OHEMKEEP: 131072
  BALANCE_WEIGHTS: [0.4, 1]
TRAIN:
  IMAGE_SIZE:
  - 520
  - 520
  BASE_SIZE: 520
  BATCH_SIZE_PER_GPU: 12
  SHUFFLE: true
  BEGIN_EPOCH: 0
  END_EPOCH: 110
  RESUME: true
  OPTIMIZER: sgd
  LR: 0.001
  WD: 0.0001
  NONBACKBONE_KEYWORDS: ['cls', 'aux', 'ocr']
  NONBACKBONE_MULT: 10
  MOMENTUM: 0.9
  NESTEROV: false
  FLIP: true
  MULTI_SCALE: true
  DOWNSAMPLERATE: 1
  IGNORE_LABEL: 255
  SCALE_FACTOR: 16
  SIGMA: 0.25
  ALT_EVERY: 2
TEST:
  # MODEL_FILE: 'hrnet_ocr_cocostuff_3965_torch04.pth'
  MODEL_FILE: 'pretrained_models/cocostuff10k_025.pth'
  SCALE_LIST: (1.0,)
  IMAGE_SIZE:
  - 520
  - 520
  BASE_SIZE: 520
  BATCH_SIZE_PER_GPU: 6
  NUM_SAMPLES: 100
  FLIP_TEST: false
  MULTI_SCALE: false